### ISSUE TITLE
CPSplitView autosave does not restore proper position

### ISSUE THREAD

**Issue by BlairDuncan** [cappuccino/cappuccino#1559]
As discussed here:
https://github.com/cappuccino/cappuccino/commit/ab3f2607579d2346d95014007065f48650e1a3f2#commitcomment-1384644

To reproduce the issue use the Manual CPSplitViewTest.
With IB add a autosave name and re nib2cib. Load the test file and move the vertical splitter.
Every time the app is loaded the vertical splitter comes back in a different location.

**Comment by daboe01** [comment]
@BlairDuncan i just ran into a similar issue:
im my case, the positioning broke when the splitter was inside a CPTabView.
as it turns out, the culprit is  `[CPTabView layoutSubviews]`.
my crude solution is to add   `[self _restoreFromAutosaveIfNeeded] ` at the end of  ` CPSplitView`'s  ` setFrameSize: `

**Comment by daboe01** [comment]
i have to add that i do not use nib2cib, so my issue and fix may be unrelated.
